In [2]:
import numpy as np

In [3]:
mylist = [1.,2.,3.,4.]
mynparray = np.array(mylist)
mynparray

array([ 1.,  2.,  3.,  4.])

In [5]:
one_vector = np.ones(4)
print one_vector

[ 1.  1.  1.  1.]


In [8]:
one_2D_array = np.ones([2,4])
print one_2D_array

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [10]:
empty_vector = np.empty(5)
print empty_vector

[  1.09364000e-316   1.25121374e-316   6.92608487e-310   7.87432736e-317
   2.37151510e-322]


In [11]:
mynparray[2]

3.0

In [15]:
my_matrix = np.array([[1,2,3],[4,5,6]])
my_matrix
print my_matrix[1,2]

6


In [16]:
print my_matrix[0:2,2]

[3 6]


In [18]:
print my_matrix[0,0:3]

[1 2 3]


In [19]:
fib_indices = np.array([1,1,2,3])

In [20]:
random_vector = np.random.random(10)

In [23]:
print random_vector
print random_vector[fib_indices]

[ 0.47949875  0.34719173  0.64558451  0.59929833  0.67942653  0.72502322
  0.0086633   0.87708195  0.59984062  0.22486608]
[ 0.34719173  0.34719173  0.64558451  0.59929833]


In [24]:
my_vector = np.array([1,2,3,4])
select_index = np.array([False,True,False,True])
print my_vector[select_index]

[2 4]


In [25]:
my_array = np.array([1.,2.,3.,4.])

In [26]:
print my_array*my_array

[  1.   4.   9.  16.]


In [28]:
print my_array**2

[  1.   4.   9.  16.]


In [30]:
print my_array + np.ones(4)

[ 2.  3.  4.  5.]


In [31]:
print my_array/3

[ 0.33333333  0.66666667  1.          1.33333333]


In [32]:
print my_array / np.array([2.,3.,4.,5])

[ 0.5         0.66666667  0.75        0.8       ]


In [33]:
print np.sum(my_array)

10.0


In [34]:
print np.average(my_array)

2.5


In [35]:
array1 = np.array([1., 2., 3., 4.])
array2 = np.array([2., 3., 4., 5.])

In [36]:
print np.dot(array1,array2)

40.0


In [37]:
print np.sum(array1*array2)

40.0


In [38]:
my_features = np.array([[1., 2.], [3., 4.], [5., 6.], [7., 8.]])
print my_features

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [39]:
my_weights = np.array([0.4, 0.5])
print my_weights

[ 0.4  0.5]


In [42]:
my_predictions = np.dot(my_features,my_weights)
print my_predictions

[ 1.4  3.2  5.   6.8]


In [47]:
my_matrix = my_features
my_array = np.array([0.3,0.4, 0.5, 0.6])

In [48]:
print np.dot(my_array, my_matrix)

[  8.2  10. ]


In [49]:
matrix_1 = np.array([[1.,2.,3.],[4.,5.,6.]])
print matrix_1

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [50]:
matrix_2 = np.array([[1.,2.],[3.,4.],[5.,6.]])
print matrix_2

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [51]:
print np.dot(matrix1,matrix2)

NameError: name 'matrix1' is not defined