In [1]:
import numpy as np

In [5]:
mylist = [1.,2.,3.,4.]
mynparray = np.array(mylist)
mynparray

array([ 1.,  2.,  3.,  4.])

In [9]:
mylist

[1.0, 2.0, 3.0, 4.0]

In [8]:
one_vector = np.ones(4)
print one_vector

[ 1.  1.  1.  1.]


In [10]:
one2Darray = np.ones((2,4))
print one2Darray

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [11]:
zero_vector = np.zeros(4)
print zero_vector

[ 0.  0.  0.  0.]


In [13]:
empty_vector = np.empty(5)
print empty_vector

[  2.33456848e-316   2.34782208e-316   6.93808077e-310   6.93808077e-310
   2.37151510e-322]


In [15]:
mynparray[2]

3.0

In [17]:
my_matrix = np.array([[1,2,3],[4,5,6]])
print my_matrix

[[1 2 3]
 [4 5 6]]


In [18]:
print my_matrix[1,2]

6


In [19]:
print my_matrix[0:2,2]

[3 6]


In [20]:
print my_matrix[0,0:3]

[1 2 3]


In [21]:
fib_indices = np.array([1,1,2,3])
random_vector = np.random.random(10)
print random_vector

[ 0.05831415  0.31128555  0.13042421  0.99124232  0.51965231  0.75089528
  0.74377091  0.54089665  0.1579456   0.77496135]


In [22]:
print random_vector[fib_indices]

[ 0.31128555  0.31128555  0.13042421  0.99124232]


In [24]:
my_vector = np.array([1,2,3,4])
select_index = np.array([True,False,True,False])
print my_vector[select_index]

[1 3]


In [25]:
select_cols = np.array([True,False,True])
select_rows = np.array([False,True])

In [26]:
print my_matrix[select_rows,:]

[[4 5 6]]


In [27]:
print my_matrix[:,select_cols]

[[1 3]
 [4 6]]


In [28]:
my_array = np.array([1.,2.,3.,4.])
print my_array*my_array

[  1.   4.   9.  16.]


In [29]:
print my_array**2

[  1.   4.   9.  16.]


In [30]:
print my_array - np.ones(4)

[ 0.  1.  2.  3.]


In [31]:
print my_array/3

[ 0.33333333  0.66666667  1.          1.33333333]


In [32]:
print my_array / np.array([2., 3., 4., 5.,])

[ 0.5         0.66666667  0.75        0.8       ]


In [33]:
print np.sum(my_array)

10.0


In [34]:
print np.average(my_array)

2.5


In [35]:
print np.sum(my_array)/len(my_array)

2.5


In [36]:
array1 = np.array([1.,2.,3.,4.])
array2 = np.array([2.,3.,4.,5.])
print np.dot(array1,array2)

40.0


In [37]:
print np.sum(array1*array2)

40.0


In [38]:
array1_mag = np.sqrt(np.dot(array1,array1))
print array1_mag

5.47722557505


In [39]:
print np.sqrt(np.sum(array1*array1))

5.47722557505


In [40]:
my_features = np.array([[1.,2.],[3.,4.],[5.,6.],[7.,8.]])
print my_features

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [41]:
my_weights = np.array([0.4,0.5])
print my_weights

[ 0.4  0.5]


In [42]:
my_prediction = np.dot(my_features,my_weights)
print my_prediction

[ 1.4  3.2  5.   6.8]
